---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.6.0

platforms:
  - name: centos-6.5
    driver_config:
      box: opscode-centos-6.5
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[slice_rs-mysql::default]
    attributes:
      cloud:
        provider: 'vagrant'
        public_ips: ['100.64.1.1']
        private_ips: ['10.0.2.15']
      rs-mysql:
        backup:
          lineage: 'lineage'
        server_root_password: rootpass
        server_repl_password: realpass
        server_usage: dedicated
        application_username: appuser
        application_password: apppass
        application_database_name: app_test
      rightscale:
        instance_uuid: '1111111'